-- Create audit_logs table
CREATE TABLE IF NOT EXISTS audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name text NOT NULL,
    operation text NOT NULL, -- INSERT, UPDATE, DELETE
    record_id bigint NOT NULL,
    old_data jsonb,
    new_data jsonb,
    changed_by text DEFAULT 'SYSTEM',
    changed_at timestamptz DEFAULT now()
);

-- Performance အတွက် Index များ ထည့်သွင်းခြင်း
CREATE INDEX IF NOT EXISTS idx_audit_table_name ON audit_logs(table_name);
CREATE INDEX IF NOT EXISTS idx_audit_changed_at ON audit_logs(changed_at);
