-- 1. Create roles table
CREATE TABLE IF NOT EXISTS roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

-- 2. Create permissions table
CREATE TABLE IF NOT EXISTS permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

-- 3. Create role_permissions junction table
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id bigint REFERENCES roles(id) ON DELETE CASCADE,
    permission_id bigint REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- 4. Create user_roles mapping table
CREATE TABLE IF NOT EXISTS user_roles (
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    role_id bigint REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);
